package net.darkhax.colourfulmobs;

import java.util.Arrays;

import net.darkhax.colourfulmobs.common.CommonProxy;
import net.darkhax.colourfulmobs.lib.Constants;
import net.darkhax.colourfulmobs.common.items.ItemColorWand;
import net.minecraft.item.Item;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Constants.MOD_ID, name = Constants.MOD_NAME, version = Constants.VERSION_NUMBER)
public class ColourfulMobs {

	@SidedProxy(clientSide = Constants.CLIENT_PROXY_CLASS, serverSide = Constants.SERVER_PROXY_CLASS)
	public static CommonProxy proxy;

	@Mod.Instance(Constants.MOD_ID)
	public static ColourfulMobs instance;

	public static Item itemColorWand = new ItemColorWand();
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent pre) {

		setModInfo(pre.getModMetadata());
		proxy.registerSidedEvents();
		GameRegistry.registerItem(itemColorWand, "colorWand", Constants.MOD_ID);
	}

	void setModInfo(ModMetadata meta) {

		meta.authorList = Arrays.asList("Darkhax");
		meta.logoFile = "";
		meta.credits = "Maintained by Darkhax";
		meta.description = "More Swords provides a magnificent chain of lustrous new swords that expound upon the foundation of Minecraft weaponry. Razor sharp swords of magic as well as stronger, more practical blaes!";
		meta.url = "http://darkhax.net";
		meta.autogenerated = false;
	}
}